spring:
  application.name: mc
  profiles.active: dev
server:
  port: 8080
  context-path: /mc
---
spring:

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etrade
    username: root
    password: root
